### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by shaiful73** [damob-byun/WireGuardNTSharp#5]
OpenAdapter Fail And Now Start Create... : 1168
Unhandled exception. System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at WireGuardNT_PInvoke.Adapter.ParseConfFile(String[] lines, WgConfig& wgConfig) in C:\Devloper\WireGuardNTSharp\WireGuardNT-PInvoke\Adapter.cs:line 188
   at WireGuardCli.Program.Main(String[] args) in C:\Devloper\WireGuardNTSharp\WireGuard-Cli\Program.cs:line 118

**Comment by damob-byun** [comment]
It looks like you didn't write the host address correctly or it's a DNS issue.
Try writing the IP address in the address line of your config file
